import React, { createContext, useContext, useState } from 'react';

type Language = 'az' | 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.skills': 'Skills',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.title': 'Babak Gasimzade',
    'hero.subtitle': 'I develop web and mobile applications with React, React Native and modern technologies.',
    'hero.cta': 'Get in Touch',
    'hero.cv': 'Download CV',
    
    // About Section
    'about.title': 'About Me',
    'about.subtitle': 'I am an expert in modern technologies as a Mobile and Frontend Developer.',
    'about.journey': 'My Journey as a Mobile & Frontend Developer',
    'about.description1': "I am a passionate developer in web and mobile application development. I focus on continuous learning in React, React Native and modern web technologies.",
    'about.description2': 'I have built a strong foundation in frontend development and am gaining experience in React Native mobile application development. Every project is a new learning opportunity for me.',
    'about.description3': 'I value teamwork and show sensitivity in code quality and user experience. I am trying to specialize in cross-platform development.',
    'about.focus': 'Areas I Focus On',
    'about.projects': 'Projects',
    'about.projectsDesc': 'Personal and educational projects',
    'about.teamProjects': 'Team Projects',
    'about.teamProjectsDesc': 'Group works',
    'about.experience': 'Experience',
    'about.experienceDesc': 'Active learning process',
    'about.experienceYear': '1 Year',
    'about.service1': 'Responsive Web Design',
    'about.service2': 'React.js Applications',
    'about.service3': 'React Native Mobile Apps',
    'about.service4': 'Cross-platform Development',
    'about.service5': 'Modern UI/UX Design',
    'about.service6': 'Mobile App Deployment',
    
    // Skills Section
    'skills.title': 'My Skills',
    'skills.subtitle': 'I am an expert in web and mobile application development.',
    'skills.frontend': 'Frontend',
    'skills.mobile': 'Mobile Development',
    'skills.tools': 'Tools & Others',
    'skills.technologies': 'Technologies & My Levels',
    'skills.learning': 'Currently Learning',
    'skills.learningDesc': 'Technologies I am actively learning for continuous development',
    'skills.level.good': 'Good',
    'skills.level.veryGood': 'Very Good',
    'skills.level.medium': 'Medium',
    'skills.tech.react': 'React',
    'skills.tech.reactNative': 'React Native',
    'skills.tech.javascript': 'JavaScript',
    'skills.tech.htmlcss': 'HTML/CSS',
    'skills.tech.expo': 'Expo',
    'skills.tech.typescript': 'TypeScript',
    'skills.tech.figma': 'Figma',
    'skills.tech.tailwind': 'Tailwind',
    'skills.learning.flutter': 'Flutter',
    'skills.learning.swift': 'Swift',
    'skills.learning.kotlin': 'Kotlin',
    'skills.learning.nextjs': 'Next.js',
    'skills.learning.testing': 'Testing',
    
    // Portfolio Section
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'Some of the projects I have developed.',
    'portfolio.all': 'All',
    'portfolio.web': 'Web',
    'portfolio.mobile': 'Mobile',
    'portfolio.fullstack': 'Full Stack',
    'portfolio.viewProject': 'View Project',
    'portfolio.viewCode': 'View Code',
    'portfolio.technologies': 'Technologies',
    'portfolio.features': 'Features',
    'portfolio.liveDemo': 'Live Demo',
    'portfolio.github': 'GitHub',
    'portfolio.viewDetails': 'View Details',
    'portfolio.moreProjects': 'Want to see more projects?',
    'portfolio.moreProjectsDesc': 'You can find more projects on my GitHub profile.',
    'portfolio.githubProfile': 'GitHub Profile',
    'portfolio.project1.title': 'E-Commerce Platform',
    'portfolio.project1.desc': 'Modern e-commerce platform. Developed with React, Node.js and PostgreSQL.',
    'portfolio.project1.feature1': 'User management',
    'portfolio.project1.feature2': 'Payment system',
    'portfolio.project1.feature3': 'Admin panel',
    'portfolio.project1.feature4': 'Responsive design',
    'portfolio.project2.title': 'Task Management App',
    'portfolio.project2.desc': 'Task management application developed for team collaboration.',
    'portfolio.project2.feature1': 'Real-time updates',
    'portfolio.project2.feature2': 'Drag & drop',
    'portfolio.project2.feature3': 'Team management',
    'portfolio.project2.feature4': 'Notifications',
    'portfolio.project3.title': 'Fitness Tracker Mobile App',
    'portfolio.project3.desc': 'Mobile application developed for personal fitness tracking.',
    'portfolio.project3.feature1': 'Exercise tracking',
    'portfolio.project3.feature2': 'Calorie calculation',
    'portfolio.project3.feature3': 'Progress charts',
    'portfolio.project3.feature4': 'Reminders',
    'portfolio.project4.title': 'Portfolio Website',
    'portfolio.project4.desc': 'Modern and responsive portfolio website.',
    'portfolio.project4.feature1': 'Animations',
    'portfolio.project4.feature2': 'Responsive design',
    'portfolio.project4.feature3': 'Dark mode',
    'portfolio.project4.feature4': 'SEO optimization',
    'portfolio.project5.title': 'Weather Dashboard',
    'portfolio.project5.desc': 'Dashboard providing real-time weather information.',
    'portfolio.project5.feature1': 'Real-time data',
    'portfolio.project5.feature2': 'Charts',
    'portfolio.project5.feature3': 'Location-based',
    'portfolio.project5.feature4': '5-day forecast',
    'portfolio.project6.title': 'Social Media Clone',
    'portfolio.project6.desc': 'Instagram-like social media application.',
    'portfolio.project6.feature1': 'Real-time messaging',
    'portfolio.project6.feature2': 'Photo sharing',
    'portfolio.project6.feature3': 'Follow system',
    'portfolio.project6.feature4': 'Notifications',
    
    // Contact Section
    'contact.title': 'Contact',
    'contact.subtitle': 'Get in touch with me for your projects.',
    'contact.getInTouch': 'Get in Touch',
    'contact.ready': 'Ready to start your next project? Let\'s discuss how I can help bring your ideas to life.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.linkedin': 'LinkedIn',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.sendMessage': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.messageSent': 'Message Sent!',
    'contact.available': 'Available for Projects',
    'contact.availableDesc': 'Currently accepting new opportunities',
    'contact.placeholder.name': 'Your name',
    'contact.placeholder.email': 'your@email.com',
    'contact.placeholder.subject': 'Project inquiry',
    'contact.placeholder.message': 'Tell me about your project...',
    
    // Footer
    'footer.getInTouch': 'Get in Touch',
    'footer.ready': 'Web and mobile application projects for you. I can help you with cross-platform development.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.workTogether': 'Let\'s Work Together',
    'footer.workTogetherDesc': 'Ready to start your next project? Let\'s discuss how I can help bring your ideas to life.',
    'footer.copyright': '© 2025 Babak Gasimzade. All rights reserved.',
    'footer.madeWith': 'Made with ❤️ in Azerbaijan by BGDev',
    'footer.description': 'As a Mobile and Frontend Developer, I develop user-friendly and performant applications with modern web technologies. I am working to specialize in cross-platform development.',
    
    // About
    'about.badge': 'Mobile Developer',
  },
  az: {
    // Navigation
    'nav.home': 'Ana Səhifə',
    'nav.about': 'Haqqımda',
    'nav.skills': 'Bacarıqlar',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Əlaqə',
    
    // Hero Section
    'hero.title': 'Babək Qasımzadə',
    'hero.subtitle': 'React, React Native və müasir texnologiyalar ilə web və mobil tətbiqlər hazırlayıram.',
    'hero.cta': 'Əlaqə saxla',
    'hero.cv': 'CV Yüklə',
    
    // About Section
    'about.title': 'Haqqımda',
    'about.subtitle': 'Mobile və Frontend Developer kimi müasir texnologiyalar sahəsində mütəxəssisəm.',
    'about.journey': 'Mobile və Frontend Developer Kimi Yolculuğum',
    'about.description1': 'Web və mobil tətbiq inkişafı sahəsində tutqulu developer\'ım. React, React Native və müasir web texnologiyaları sahəsində davamlı öyrənməyə fokuslanıram.',
    'about.description2': 'Frontend inkişafı sahəsində güclü təməl yaratdım və React Native mobil tətbiq inkişafı sahəsində təcrübə qazanıram. Hər layihə mənim üçün yeni öyrənmə fürsətidir.',
    'about.description3': 'Komanda işinə dəyər verirəm və kod keyfiyyəti və istifadəçi təcrübəsi məsələlərində həssaslıq göstərirəm. Cross-platform inkişaf sahəsində ixtisaslaşmağa çalışıram.',
    'about.focus': 'Fokuslandığım Sahələr',
    'about.projects': 'Layihələr',
    'about.projectsDesc': 'Şəxsi və təhsil layihələri',
    'about.teamProjects': 'Komanda Layihələri',
    'about.teamProjectsDesc': 'Qrup işləri',
    'about.experience': 'Təcrübə',
    'about.experienceDesc': 'Aktiv öyrənmə prosesi',
    'about.experienceYear': '1 il',
    'about.service1': 'Responsive Web Design',
    'about.service2': 'React.js Applications',
    'about.service3': 'React Native Mobile Apps',
    'about.service4': 'Cross-platform Development',
    'about.service5': 'Modern UI/UX Design',
    'about.service6': 'Mobile App Deployment',
    
    // Skills Section
    'skills.title': 'Bacarıqlarım',
    'skills.subtitle': 'Web və mobil tətbiq inkişafı sahəsində mütəxəssisəm.',
    'skills.frontend': 'Frontend',
    'skills.mobile': 'Mobil İnkişaf',
    'skills.tools': 'Alətlər və Digərləri',
    'skills.technologies': 'Texnologiyalar və Səviyyələrim',
    'skills.learning': 'Hal-hazırda Öyrəndiklərim',
    'skills.learningDesc': 'Davamlı inkişaf üçün aktiv olaraq öyrəndiyim texnologiyalar',
    'skills.level.good': 'Yaxşı',
    'skills.level.veryGood': 'Çox Yaxşı',
    'skills.level.medium': 'Orta',
    'skills.tech.react': 'React',
    'skills.tech.reactNative': 'React Native',
    'skills.tech.javascript': 'JavaScript',
    'skills.tech.htmlcss': 'HTML/CSS',
    'skills.tech.expo': 'Expo',
    'skills.tech.typescript': 'TypeScript',
    'skills.tech.figma': 'Figma',
    'skills.tech.tailwind': 'Tailwind',
    'skills.learning.flutter': 'Flutter',
    'skills.learning.swift': 'Swift',
    'skills.learning.kotlin': 'Kotlin',
    'skills.learning.nextjs': 'Next.js',
    'skills.learning.testing': 'Testing',
    
    // Portfolio Section
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'Hazırladığım layihələrdən bəziləri.',
    'portfolio.all': 'Hamısı',
    'portfolio.web': 'Web',
    'portfolio.mobile': 'Mobil',
    'portfolio.fullstack': 'Full Stack',
    'portfolio.viewProject': 'Layihəyə Bax',
    'portfolio.viewCode': 'Koda Bax',
    'portfolio.technologies': 'Texnologiyalar',
    'portfolio.features': 'Xüsusiyyətlər',
    'portfolio.liveDemo': 'Canlı Demo',
    'portfolio.github': 'GitHub',
    'portfolio.viewDetails': 'Detalları Görüntülə',
    'portfolio.moreProjects': 'Daha çox layihə görmək istəyirsiniz?',
    'portfolio.moreProjectsDesc': 'Mənim GitHub profilimdə daha çox layihəni tapa bilərsiniz.',
    'portfolio.githubProfile': 'GitHub Profilim',
    'portfolio.project1.title': 'E-Commerce Platforması',
    'portfolio.project1.desc': 'Modern e-commerce platformu. React, Node.js və PostgreSQL ilə yaradılmışdır.',
    'portfolio.project1.feature1': 'İstifadəçi idarəetməsi',
    'portfolio.project1.feature2': 'Ödəniş sistemi',
    'portfolio.project1.feature3': 'Admin paneli',
    'portfolio.project1.feature4': 'Responsiv dizayn',
    'portfolio.project2.title': 'Vəzifə idarəetmə tətbiqi',
    'portfolio.project2.desc': 'Vəzifə idarəetmə tətbiqi komandaya təminat üçün yaradılmışdır.',
    'portfolio.project2.feature1': 'Real-vaxt müdafiə',
    'portfolio.project2.feature2': 'Sürüşdürmə və sürüşdürmə',
    'portfolio.project2.feature3': 'Komanda idarəetməsi',
    'portfolio.project2.feature4': 'Bildirişlər',
    'portfolio.project3.title': 'Fitness İzləyici Mobil Tətbiqi',
    'portfolio.project3.desc': 'Şəxsi fitness izləmə üçün yaradılmış mobil tətbiq.',
    'portfolio.project3.feature1': 'İscək izləməsi',
    'portfolio.project3.feature2': 'Kalori hesablanması',
    'portfolio.project3.feature3': 'Progres şəbəkələri',
    'portfolio.project3.feature4': 'Xatırlatmalar',
    'portfolio.project4.title': 'Portfolio Saytı',
    'portfolio.project4.desc': 'Modern və responsiv portfolio sayt.',
    'portfolio.project4.feature1': 'Animasiyalar',
    'portfolio.project4.feature2': 'Responsiv dizayn',
    'portfolio.project4.feature3': 'Açıq mövzu',
    'portfolio.project4.feature4': 'SEO optimizasiyası',
    'portfolio.project5.title': 'Hava Proyekt Dashboards',
    'portfolio.project5.desc': 'Real-vaxt hava məlumatlarını təmin edən dashboards.',
    'portfolio.project5.feature1': 'Real-vaxt məlumat',
    'portfolio.project5.feature2': 'Şəbəkələr',
    'portfolio.project5.feature3': 'Mövzu əsasında',
    'portfolio.project5.feature4': '5 günlük proqnoz',
    'portfolio.project6.title': 'Sosial Medya Klonu',
    'portfolio.project6.desc': 'Instagram-kimi sosial medya tətbiqi.',
    'portfolio.project6.feature1': 'Real-vaxt mesajlaşma',
    'portfolio.project6.feature2': 'Şəkil paylaşma',
    'portfolio.project6.feature3': 'İzləmə sistemi',
    'portfolio.project6.feature4': 'Bildirişlər',
    
    // Contact Section
    'contact.title': 'Əlaqə',
    'contact.subtitle': 'Layihələriniz üçün mənimlə əlaqə saxlayın.',
    'contact.getInTouch': 'Əlaqə Saxla',
    'contact.ready': 'Növbəti layihənizi başlamağa hazırsınız? Fikirlərinizi həyata keçirməkdə sizə necə kömək edə biləcəyimi müzakirə edək.',
    'contact.name': 'Ad',
    'contact.email': 'E-poçt',
    'contact.phone': 'Əlaqə nömrəsi',
    'contact.linkedin': 'LinkedIn',
    'contact.subject': 'Mövzu',
    'contact.message': 'Mesaj',
    'contact.sendMessage': 'Mesaj Göndər',
    'contact.sending': 'Göndərilir...',
    'contact.messageSent': 'Mesaj Göndərildi!',
    'contact.available': 'Layihələr üçün Mövcuddur',
    'contact.availableDesc': 'Hal-hazırda yeni imkanları qəbul edir',
    'contact.placeholder.name': 'Adınız',
    'contact.placeholder.email': 'sizin@email.com',
    'contact.placeholder.subject': 'Layihə sorğusu',
    'contact.placeholder.message': 'Layihəniz haqqında mənə danışın...',
    
    // Footer
    'footer.getInTouch': 'Əlaqə Saxla',
    'footer.ready': 'Sizin üçün web və mobil tətbiq layihələri. Cross-platform inkişaf sahəsində sizə kömək edə bilərəm.',
    'footer.quickLinks': 'Sürətli Linklər',
    'footer.contact': 'Əlaqə',
    'footer.workTogether': 'Gəlin Birlikdə İşləyək',
    'footer.workTogetherDesc': 'Növbəti layihənizi başlamağa hazırsınız? Fikirlərinizi həyata keçirməkdə sizə necə kömək edə biləcəyimi müzakirə edək.',
    'footer.copyright': '© 2025 Babək Qasımzadə. Bütün hüquqlar qorunur.',
    'footer.madeWith': 'Azərbaycanda ❤️ ilə BGDev tərəfindən hazırlanıb',
    'footer.description': 'Mobil və Frontend Developer kimi, mənimlə modern web texnologiyaları ilə istifadəçi dostu və işləməli tətbiqlər yaradıram. Cross-platform inkişaf sahəsində ixtisaslaşmağa çalışıram.',
    
    // About
    'about.badge': 'Mobil Developer',
  },
  tr: {
    // Navigation
    'nav.home': 'Ana Sayfa',
    'nav.about': 'Hakkımda',
    'nav.skills': 'Yetenekler',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'İletişim',
    
    // Hero Section
    'hero.title': 'Babək Qasımzadə',
    'hero.subtitle': 'React, React Native ve modern teknolojiler ile web ve mobil uygulamalar geliştiriyorum.',
    'hero.cta': 'İletişime Geç',
    'hero.cv': 'CV İndir',
    
    // About Section
    'about.title': 'Hakkımda',
    'about.subtitle': 'Mobile ve Frontend Developer olarak modern teknolojiler konusunda uzmanım.',
    'about.journey': 'Mobile ve Frontend Developer Olarak Yolculuğum',
    'about.description1': "Web ve mobil uygulama geliştirme alanında tutkulu bir developer'ım. React, React Native ve modern web teknolojileri konusunda sürekli öğrenmeye odaklanıyorum.",
    'about.description2': 'Frontend geliştirme konusunda güçlü bir temel oluşturdum və React Native ile mobil uygulama geliştirme konusunda deneyim kazanıyorum. Her proje benim için yeni bir öğrenme fırsatı.',
    'about.description3': 'Takım çalışmasına önem veriyor, kod kalitesi ve kullanıcı deneyimi konularında hassasiyet gösteriyorum. Cross-platform geliştirme konusunda uzmanlaşmaya çalışıyorum.',
    'about.focus': 'Odaklandığım Alanlar',
    'about.projects': 'Projeler',
    'about.projectsDesc': 'Kişisel ve eğitim projeleri',
    'about.teamProjects': 'Takım Projeleri',
    'about.teamProjectsDesc': 'Grup çalışmaları',
    'about.experience': 'Deneyim',
    'about.experienceDesc': 'Aktif öğrenme süreci',
    'about.experienceYear': '1 yıl',
    'about.service1': 'Responsive Web Design',
    'about.service2': 'React.js Applications',
    'about.service3': 'React Native Mobile Apps',
    'about.service4': 'Cross-platform Development',
    'about.service5': 'Modern UI/UX Design',
    'about.service6': 'Mobile App Deployment',
    
    // Skills Section
    'skills.title': 'Yeteneklerim',
    'skills.subtitle': 'Web ve mobil uygulama geliştirme konusunda uzmanım.',
    'skills.frontend': 'Frontend',
    'skills.mobile': 'Mobil Geliştirme',
    'skills.tools': 'Araçlar ve Diğerleri',
    'skills.technologies': 'Teknolojiler ve Seviyelerim',
    'skills.learning': 'Şu Anda Öğrendiklerim',
    'skills.learningDesc': 'Sürekli gelişim için aktif olarak öğrendiğim teknolojiler',
    'skills.level.good': 'İyi',
    'skills.level.veryGood': 'Çok İyi',
    'skills.level.medium': 'Orta',
    'skills.tech.react': 'React',
    'skills.tech.reactNative': 'React Native',
    'skills.tech.javascript': 'JavaScript',
    'skills.tech.htmlcss': 'HTML/CSS',
    'skills.tech.expo': 'Expo',
    'skills.tech.typescript': 'TypeScript',
    'skills.tech.figma': 'Figma',
    'skills.tech.tailwind': 'Tailwind',
    'skills.learning.flutter': 'Flutter',
    'skills.learning.swift': 'Swift',
    'skills.learning.kotlin': 'Kotlin',
    'skills.learning.nextjs': 'Next.js',
    'skills.learning.testing': 'Testing',
    
    // Portfolio Section
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'Geliştirdiğim projelerden bazıları.',
    'portfolio.all': 'Tümü',
    'portfolio.web': 'Web',
    'portfolio.mobile': 'Mobil',
    'portfolio.fullstack': 'Full Stack',
    'portfolio.viewProject': 'Projeyi Görüntüle',
    'portfolio.viewCode': 'Kodu Görüntüle',
    'portfolio.technologies': 'Teknolojiler',
    'portfolio.features': 'Özellikler',
    'portfolio.liveDemo': 'Canlı Demo',
    'portfolio.github': 'GitHub',
    'portfolio.viewDetails': 'Detayları Görüntüle',
    'portfolio.moreProjects': 'Daha çok proje görmek ister misiniz?',
    'portfolio.moreProjectsDesc': 'GitHub profilimde daha çok projeyi bulabilirsiniz.',
    'portfolio.githubProfile': 'GitHub Profilim',
    'portfolio.project1.title': 'E-Ticaret Platformu',
    'portfolio.project1.desc': 'Modern e-ticaret platformu. React, Node.js ve PostgreSQL ile geliştirilmiştir.',
    'portfolio.project1.feature1': 'Kullanıcı yönetimi',
    'portfolio.project1.feature2': 'Ödeme sistemi',
    'portfolio.project1.feature3': 'Admin paneli',
    'portfolio.project1.feature4': 'Responsif tasarım',
    'portfolio.project2.title': 'Görev Yönetim Uygulaması',
    'portfolio.project2.desc': 'Takıma tümleşik görev yönetim uygulaması.',
    'portfolio.project2.feature1': 'Gerçek zamanlı güncellemeler',
    'portfolio.project2.feature2': 'Sürüştürme ve sürüştürme',
    'portfolio.project2.feature3': 'Takım yönetimi',
    'portfolio.project2.feature4': 'Bildirimler',
    'portfolio.project3.title': 'Fitness Takipci Mobil Uygulaması',
    'portfolio.project3.desc': 'Kişisel fitness takibi için geliştirilmiş mobil uygulama.',
    'portfolio.project3.feature1': 'Egzersiz takibi',
    'portfolio.project3.feature2': 'Kalori hesaplama',
    'portfolio.project3.feature3': 'İlerleme grafikleri',
    'portfolio.project3.feature4': 'Hatırlatıcılar',
    'portfolio.project4.title': 'Portfolio Web Sitesi',
    'portfolio.project4.desc': 'Modern ve responsive portfolio web sitesi.',
    'portfolio.project4.feature1': 'Animasyonlar',
    'portfolio.project4.feature2': 'Responsif tasarım',
    'portfolio.project4.feature3': 'Karanlık mod',
    'portfolio.project4.feature4': 'SEO optimizasyonu',
    'portfolio.project5.title': 'Hava Durumu Paneli',
    'portfolio.project5.desc': 'Gerçek zamanlı hava bilgilerini sağlayan bir dashboard.',
    'portfolio.project5.feature1': 'Gerçek zamanlı veri',
    'portfolio.project5.feature2': 'Grafikler',
    'portfolio.project5.feature3': 'Konum bazlı',
    'portfolio.project5.feature4': '5 günlük tahmin',
    'portfolio.project6.title': 'Sosyal Medya Klonu',
    'portfolio.project6.desc': 'Instagram benzeri bir sosyal medya uygulaması.',
    'portfolio.project6.feature1': 'Gerçek zamanlı mesajlaşma',
    'portfolio.project6.feature2': 'Fotoğraf paylaşma',
    'portfolio.project6.feature3': 'Takip sistemi',
    'portfolio.project6.feature4': 'Bildirimler',
    
    // Contact Section
    'contact.title': 'İletişim',
    'contact.subtitle': 'Projeleriniz için benimle iletişime geçin.',
    'contact.getInTouch': 'İletişime Geç',
    'contact.ready': 'Bir sonraki projenizi başlatmaya hazır mısınız? Fikirlerinizi hayata geçirmenize nasıl yardımcı olabileceğimi tartışalım.',
    'contact.name': 'Ad',
    'contact.email': 'E-posta',
    'contact.phone': 'Telefon',
    'contact.linkedin': 'LinkedIn',
    'contact.subject': 'Konu',
    'contact.message': 'Mesaj',
    'contact.sendMessage': 'Mesaj Gönder',
    'contact.sending': 'Gönderiliyor...',
    'contact.messageSent': 'Mesaj Gönderildi!',
    'contact.available': 'Projeler İçin Müsait',
    'contact.availableDesc': 'Şu anda yeni fırsatları kabul ediyor',
    'contact.placeholder.name': 'Adınız',
    'contact.placeholder.email': 'sizin@email.com',
    'contact.placeholder.subject': 'Proje sorgusu',
    'contact.placeholder.message': 'Projeniz hakkında bana anlatın...',
    
    // Footer
    'footer.getInTouch': 'İletişime Geç',
    'footer.ready': 'Sizin için web ve mobil uygulama projeleri. Cross-platform geliştirme konusunda size yardımcı olabilirim.',
    'footer.quickLinks': 'Hızlı Linkler',
    'footer.contact': 'İletişim',
    'footer.workTogether': 'Birlikte Çalışalım',
    'footer.workTogetherDesc': 'Bir sonraki projenizi başlatmaya hazır mısınız? Fikirlerinizi hayata geçirmenize nasıl yardımcı olabileceğimi tartışalım.',
    'footer.copyright': '© 2025 Babək Qasımzadə. Tüm hakları saklıdır.',
    'footer.madeWith': 'Azerbaycan\'da ❤️ ile BGDev tarafından yapıldı',
    'footer.description': 'Mobil ve Frontend Developer kimi, mənimlə modern web texnologiyaları ilə istifadəçi dostu və işləməli tətbiqlər yaradıram. Cross-platform geliştirme konusunda size yardımcı olabilirim.',
    
    // About
    'about.badge': 'Mobil Developer',
  },
};

export const LanguageProvider = ({ children }: { children: any }) => {
  const [language, setLanguage] = useState('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 