import React, { createContext, useContext, useState } from 'react';

type Language = 'az' | 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.skills': 'Skills',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.title': 'Babak Gasimzade',
    'hero.subtitle': 'I develop web and mobile applications with React, React Native and modern technologies.',
    'hero.description': 'Passionate Mobile & Frontend Developer creating innovative digital experiences with React Native, React, and modern web technologies.',
    'hero.welcome': 'Welcome to my portfolio',
    'hero.cta': 'Get in Touch',
    'hero.cv': 'Download CV',
    
    // About Section
    'about.title': 'About Me',
    'about.subtitle': 'I am a passionate Junior Frontend and Mobile Developer with hands-on experience in React, React Native, and modern web technologies.',
    'about.journey': 'My Journey as a Mobile & Frontend Developer',
    'about.description1': "With a solid foundation in JavaScript and React ecosystem, I've successfully completed several projects that showcase my ability to build functional, user-friendly applications.",
    'about.description2': 'I focus on writing clean, well-documented code and following best practices to create maintainable and efficient solutions.',
    'about.description3': 'I am committed to continuous learning and staying updated with industry trends, which helps me deliver modern, high-quality applications.',
    'about.focus': 'Areas I Focus On',
    'about.projects': 'Projects',
    'about.projectsDesc': 'Personal and educational projects',
    'about.teamProjects': 'Team Projects',
    'about.teamProjectsDesc': 'Group works',
    'about.experience': 'Experience',
    'about.experienceDesc': 'Active learning process',
    'about.experienceYear': '1 Year',
    'about.service1': 'Responsive Web Design',
    'about.service2': 'React.js Applications',
    'about.service3': 'React Native Mobile Apps',
    'about.service4': 'Cross-platform Development',
    'about.service5': 'Modern UI/UX Design',
    'about.service6': 'Mobile App Deployment',
    
    // Skills Section
    'skills.title': 'My Skills',
    'skills.subtitle': 'Technologies and tools I use to bring ideas to life',
    'skills.frontend': 'Frontend',
    'skills.mobile': 'Mobile Development',
    'skills.tools': 'Tools & Others',
    'skills.technologies': 'Technologies & My Levels',
    'skills.learning': 'Currently Learning',
    'skills.learningDesc': 'Technologies I am actively learning for continuous development',
    'skills.level.good': 'Good',
    'skills.level.veryGood': 'Very Good',
    'skills.level.medium': 'Medium',
    'skills.tech.react': 'React',
    'skills.tech.reactNative': 'React Native',
    'skills.tech.javascript': 'JavaScript',
    'skills.tech.htmlcss': 'HTML/CSS',
    'skills.tech.expo': 'Expo',
    'skills.tech.typescript': 'TypeScript',
    'skills.tech.figma': 'Figma',
    'skills.tech.tailwind': 'Tailwind',
    'skills.learning.flutter': 'Flutter',
    'skills.learning.swift': 'Swift',
    'skills.learning.kotlin': 'Kotlin',
    'skills.learning.nextjs': 'Next.js',
    'skills.learning.testing': 'Testing',
    'skills.treeTitle': 'My Learning Path',
    'skills.treeDesc': 'Interactive skill tree showing my development journey and how technologies connect',
    
    // Portfolio Section
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'A collection of my web development projects showcasing my learning journey.',
    'portfolio.all': 'All',
    'portfolio.web': 'Web',
'portfolio.mobile': 'Mobile',
'portfolio.responsive': 'Responsive',
'portfolio.interactive': 'Interactive',
    'portfolio.viewProject': 'View Project',
    'portfolio.viewCode': 'View Code',
    'portfolio.technologies': 'Technologies',
    'portfolio.features': 'Features',
    'portfolio.liveDemo': 'Live Demo',
    'portfolio.github': 'GitHub',
    'portfolio.viewDetails': 'View Details',
    'portfolio.moreProjects': 'Want to see more projects?',
    'portfolio.moreProjectsDesc': 'You can find more projects on my GitHub profile.',
    'portfolio.githubProfile': 'GitHub Profile',
    'portfolio.project1.title': 'BGAutoSales - E-commerce Platform',
    'portfolio.project1.desc': 'A complete e-commerce website for my small business built with HTML5, CSS3, and JavaScript. Features product catalog, shopping cart, and responsive design for mobile and desktop users.',
    'portfolio.project1.feature1': 'Product catalog & search',
    'portfolio.project1.feature2': 'Shopping cart functionality',
    'portfolio.project1.feature3': 'Responsive mobile design',
    'portfolio.project1.feature4': 'Payment integration ready',
    'portfolio.project2.title': 'Buldum App - Marketplace Platform',
    'portfolio.project2.desc': 'A professional marketplace application for selling cars, real estate, and devices. Developed the "Post Ad" feature with categories, subcategories, API integration, and advanced functionality.',
    'portfolio.project2.feature1': 'Post ad functionality',
    'portfolio.project2.feature2': 'Category management',
    'portfolio.project2.feature3': 'API integration',
    'portfolio.project2.feature4': 'Advanced search filters',
    'portfolio.project3.title': 'UDEMY-BG - Learning Platform Clone',
    'portfolio.project3.desc': 'A full-stack Udemy clone built with React, Node.js, and MongoDB. Features user authentication, course management, video streaming, and payment processing.',
    'portfolio.project3.feature1': 'User authentication',
    'portfolio.project3.feature2': 'Course management',
    'portfolio.project3.feature3': 'Video streaming',
    'portfolio.project3.feature4': 'Payment integration',
          'portfolio.project4.title': 'Vesh.az - Travel Platform',
      'portfolio.project4.desc': 'Major travel platform with 80k+ users in Baku. Contributed to both web and mobile app development, focusing on UI/UX design. Available on Google Play Store and App Store.',
    'portfolio.project4.feature1': 'Responsive web design',
    'portfolio.project4.feature2': 'Mobile app UI/UX',
    'portfolio.project4.feature3': 'Travel booking interface',
    'portfolio.project4.feature4': 'Cross-platform compatibility',
    'portfolio.project5.title': 'E-Recommender System - Thesis',
    'portfolio.project5.desc': 'Bachelor thesis project: An intelligent recommendation system built with Python and Flask. Implements machine learning algorithms for personalized content suggestions.',
    'portfolio.project5.feature1': 'Machine learning algorithms',
    'portfolio.project5.feature2': 'Recommendation engine',
    'portfolio.project5.feature3': 'Data analysis',
    'portfolio.project5.feature4': 'Academic research',
    'portfolio.project6.title': 'Frontend Portfolio',
    'portfolio.project6.desc': 'My previous portfolio website showcasing frontend development skills. Built with HTML5, CSS3, and JavaScript, featuring modern design and smooth animations.',
          'portfolio.project6.feature1': 'Modern portfolio design',
      'portfolio.project6.feature2': 'Smooth animations',
      'portfolio.project6.feature3': 'Responsive layout',
      'portfolio.project6.feature4': 'Interactive elements',
      'portfolio.project7.title': 'Todo List App',
      'portfolio.project7.desc': 'A simple and intuitive todo list application built with vanilla JavaScript. Features task creation, completion tracking, and local storage for data persistence.',
      'portfolio.project7.feature1': 'Add and delete tasks',
      'portfolio.project7.feature2': 'Mark tasks as complete',
      'portfolio.project7.feature3': 'Local storage persistence',
      'portfolio.project8.title': 'Weather App',
      'portfolio.project8.desc': 'A responsive weather application that displays current weather conditions and forecasts. Integrates with weather APIs to provide real-time data.',
          'portfolio.project8.feature1': 'Current weather display',
    'portfolio.project8.feature2': 'Weather API integration',
    'portfolio.project8.feature3': 'Responsive design',
    'portfolio.project9.title': 'Modern Portfolio Website',
    'portfolio.project9.desc': 'A modern, responsive portfolio website built with React, TypeScript, and Tailwind CSS. Features smooth animations, multi-language support, and interactive components showcasing my development skills.',
    'portfolio.project9.feature1': 'Multi-language support (EN/AZ/TR)',
    'portfolio.project9.feature2': 'Interactive animations and components',
    'portfolio.project9.feature3': 'Responsive design with modern UI/UX',
    'portfolio.codeEditor': 'Live Code Editor',
    'portfolio.codeEditorDesc': 'See my coding style and approach with this interactive code example',
    'portfolio.codeEditor.hello': 'Hello',
    'portfolio.codeEditor.welcome': 'Welcome to my portfolio',
    'portfolio.timeline': 'Learning Timeline',
    'portfolio.timelineDesc': 'My development journey and learning progress over time',
    
    // Contact Section
    'contact.title': 'Contact',
    'contact.subtitle': 'Get in touch with me for your projects.',
    'contact.getInTouch': 'Get in Touch',
    'contact.ready': 'Ready to start your next project? Let\'s discuss how I can help bring your ideas to life.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.linkedin': 'LinkedIn',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.sendMessage': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.messageSent': 'Message Sent!',
    'contact.available': 'Available for Projects',
    'contact.availableDesc': 'Currently accepting new opportunities',
    'contact.placeholder.name': 'Your name',
    'contact.placeholder.email': 'your@email.com',
    'contact.placeholder.subject': 'Project inquiry',
    'contact.placeholder.message': 'Tell me about your project...',
    
    // Footer
    'footer.getInTouch': 'Get in Touch',
    'footer.ready': 'Web and mobile application projects for you. I can help you with cross-platform development.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.workTogether': 'Let\'s Work Together',
    'footer.workTogetherDesc': 'Ready to start your next project? Let\'s discuss how I can help bring your ideas to life.',
    'footer.copyright': '© 2025 Babak Gasimzade. All rights reserved.',
    'footer.madeWith': 'Made with ❤️ in Azerbaijan by BGDev',
    'footer.description': 'As a Mobile and Frontend Developer, I develop user-friendly and performant applications with modern web technologies. I am working to specialize in cross-platform development.',
    
    // About
    'about.badge': 'Mobile Developer',
  },
  az: {
    // Navigation
    'nav.home': 'Ana Səhifə',
    'nav.about': 'Haqqımda',
    'nav.skills': 'Bacarıqlar',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Əlaqə',
    
    // Hero Section
    'hero.title': 'Babək Qasımzadə',
    'hero.subtitle': 'React, React Native və müasir texnologiyalar ilə web və mobil tətbiqlər hazırlayıram.',
    'hero.description': 'React Native, React və müasir veb texnologiyaları ilə innovativ rəqəmsal təcrübələr yaradan həvəskar Mobil və Frontend Developer.',
    'hero.welcome': 'Portfolio-ma xoş gəlmisiniz',
    'hero.cta': 'Əlaqə saxla',
    'hero.cv': 'CV Yüklə',
    
    // About Section
    'about.title': 'Haqqımda',
    'about.subtitle': 'React, React Native və müasir veb texnologiyalarında praktik təcrübəsi olan həvəskarlıq Junior Frontend və Mobil Developer-əm.',
    'about.journey': 'Mobile və Frontend Developer Kimi Yolculuğum',
    'about.description1': 'JavaScript və React ekosistemində möhkəm təməllə, funksional və istifadəçi dostu tətbiqlər yaratmaq qabiliyyətimə sübut edən bir neçə layihəni uğurla tamamlamışam.',
    'about.description2': 'Təmiz, yaxşı sənədləşdirilmiş kod yazmağa və saxlanıla bilən, effektiv həllər yaratmaq üçün ən yaxşı təcrübələri izləməyə fokuslanıram.',
    'about.description3': 'Daimi öyrənməyə və sənaye tendensiyaları ilə güncəldə qalmağa sadiqəm, bu da müasir, yüksək keyfiyyətli tətbiqlər təqdim etməyə kömək edir.',
    'about.focus': 'Fokuslandığım Sahələr',
    'about.projects': 'Layihələr',
    'about.projectsDesc': 'Şəxsi və təhsil layihələri',
    'about.teamProjects': 'Komanda Layihələri',
    'about.teamProjectsDesc': 'Qrup işləri',
    'about.experience': 'Təcrübə',
    'about.experienceDesc': 'Aktiv öyrənmə prosesi',
    'about.experienceYear': '1 il',
    'about.service1': 'Responsive Web Design',
    'about.service2': 'React.js Applications',
    'about.service3': 'React Native Mobile Apps',
    'about.service4': 'Cross-platform Development',
    'about.service5': 'Modern UI/UX Design',
    'about.service6': 'Mobile App Deployment',
    
    // Skills Section
    'skills.title': 'Bacarıqlarım',
    'skills.subtitle': 'Fikirləri həyata keçirmək üçün istifadə etdiyim texnologiyalar və alətlər',
    'skills.frontend': 'Frontend',
    'skills.mobile': 'Mobil İnkişaf',
    'skills.tools': 'Alətlər və Digərləri',
    'skills.technologies': 'Texnologiyalar və Səviyyələrim',
    'skills.learning': 'Hal-hazırda Öyrəndiklərim',
    'skills.learningDesc': 'Davamlı inkişaf üçün aktiv olaraq öyrəndiyim texnologiyalar',
    'skills.level.good': 'Yaxşı',
    'skills.level.veryGood': 'Çox Yaxşı',
    'skills.level.medium': 'Orta',
    'skills.tech.react': 'React',
    'skills.tech.reactNative': 'React Native',
    'skills.tech.javascript': 'JavaScript',
    'skills.tech.htmlcss': 'HTML/CSS',
    'skills.tech.expo': 'Expo',
    'skills.tech.typescript': 'TypeScript',
    'skills.tech.figma': 'Figma',
    'skills.tech.tailwind': 'Tailwind',
    'skills.learning.flutter': 'Flutter',
    'skills.learning.swift': 'Swift',
    'skills.learning.kotlin': 'Kotlin',
    'skills.learning.nextjs': 'Next.js',
    'skills.learning.testing': 'Testing',
    'skills.treeTitle': 'Öyrənmə Yolum',
    'skills.treeDesc': 'İnteraktiv bacarıq ağacı mənim inkişaf səfərimi və texnologiyaların necə bağlandığını göstərir',
    
    // Portfolio Section
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'Öyrənmə səfərimi göstərən web development layihələrimin kolleksiyası.',
    'portfolio.all': 'Hamısı',
    'portfolio.web': 'Web',
'portfolio.mobile': 'Mobil',
'portfolio.responsive': 'Responsive',
'portfolio.interactive': 'İnteraktiv',
    'portfolio.viewProject': 'Layihəyə Bax',
    'portfolio.viewCode': 'Koda Bax',
    'portfolio.technologies': 'Texnologiyalar',
    'portfolio.features': 'Xüsusiyyətlər',
    'portfolio.liveDemo': 'Canlı Demo',
    'portfolio.github': 'GitHub',
    'portfolio.viewDetails': 'Detalları Görüntülə',
    'portfolio.moreProjects': 'Daha çox layihə görmək istəyirsiniz?',
    'portfolio.moreProjectsDesc': 'Mənim GitHub profilimdə daha çox layihəni tapa bilərsiniz.',
    'portfolio.githubProfile': 'GitHub Profilim',
    'portfolio.project1.title': 'BGAutoSales - E-ticarət Platforması',
    'portfolio.project1.desc': 'Kiçik biznesim üçün HTML5, CSS3 və JavaScript ilə yaradılmış tam e-ticarət veb saytı. Məhsul kataloqu, alış-veriş səbəti və mobil və desktop istifadəçilər üçün responsive dizayn.',
    'portfolio.project1.feature1': 'Məhsul kataloqu və axtarış',
    'portfolio.project1.feature2': 'Alış-veriş səbəti funksiyası',
    'portfolio.project1.feature3': 'Responsive mobil dizayn',
    'portfolio.project1.feature4': 'Ödəniş inteqrasiyası hazır',
    'portfolio.project2.title': 'Buldum App - Bazar Yeri Platforması',
    'portfolio.project2.desc': 'Avtomobil, əmlak və cihazların satışı üçün peşəkar bazar yeri tətbiqi. "Elan ver" funksiyasını kateqoriyalar, alt kateqoriyalar, API inteqrasiyası və təkmilləşdirilmiş funksionallıq ilə inkişaf etdirdim.',
    'portfolio.project2.feature1': 'Elan vermə funksiyası',
    'portfolio.project2.feature2': 'Kateqoriya idarəetməsi',
    'portfolio.project2.feature3': 'API inteqrasiyası',
    'portfolio.project2.feature4': 'Təkmilləşdirilmiş axtarış filtrləri',
    'portfolio.project3.title': 'UDEMY-BG - Öyrənmə Platforması Klonu',
    'portfolio.project3.desc': 'React, Node.js və MongoDB ilə yaradılmış tam yığın Udemy klonu. İstifadəçi autentifikasiyası, kurs idarəetməsi, video yayımı və ödəniş emalı.',
    'portfolio.project3.feature1': 'İstifadəçi autentifikasiyası',
    'portfolio.project3.feature2': 'Kurs idarəetməsi',
    'portfolio.project3.feature3': 'Video yayımı',
    'portfolio.project3.feature4': 'Ödəniş inteqrasiyası',
    'portfolio.project4.title': 'Vesh.az - Səyahət Platforması',
    'portfolio.project4.desc': 'Bakıda 80k+ istifadəçisi olan əsas səyahət platforması. Həm veb, həm də mobil tətbiq inkişafında iştirak etdim, UI/UX dizaynına fokuslanaraq. Google Play Store və App Store-da mövcuddur.',
    'portfolio.project4.feature1': 'Responsive veb dizaynı',
    'portfolio.project4.feature2': 'Mobil tətbiq UI/UX',
    'portfolio.project4.feature3': 'Səyahət rezervasiya interfeysi',
    'portfolio.project4.feature4': 'Cross-platform uyğunluq',
    'portfolio.project5.title': 'E-Tövsiyə Sistemi - Diplom İşi',
    'portfolio.project5.desc': 'Bakalavr diplom işi: Python və Flask ilə yaradılmış intellektual tövsiyə sistemi. Fərdiləşdirilmiş məzmun tövsiyələri üçün maşın öyrənmə alqoritmlərini tətbiq edir.',
    'portfolio.project5.feature1': 'Maşın öyrənmə alqoritmləri',
    'portfolio.project5.feature2': 'Tövsiyə mühərriki',
    'portfolio.project5.feature3': 'Məlumat analizi',
    'portfolio.project5.feature4': 'Akademik tədqiqat',
    'portfolio.project6.title': 'Frontend Portfolio',
    'portfolio.project6.desc': 'Frontend development bacarıqlarımı nümayiş etdirən əvvəlki portfolio veb saytım. HTML5, CSS3 və JavaScript ilə yaradılmış, modern dizayn və smooth animasiyalar.',
          'portfolio.project6.feature1': 'Modern portfolio dizaynı',
      'portfolio.project6.feature2': 'Smooth animasiyalar',
      'portfolio.project6.feature3': 'Responsive layout',
      'portfolio.project6.feature4': 'İnteraktiv elementlər',
      'portfolio.project7.title': 'Todo List Tətbiqi',
      'portfolio.project7.desc': 'Vanilla JavaScript ilə tikilmiş sadə və intuitiv todo list tətbiqi. Tapşırıq yaratma, tamamlama izləmə və məlumatların saxlanması üçün local storage xüsusiyyətləri.',
      'portfolio.project7.feature1': 'Tapşırıq əlavə et və sil',
      'portfolio.project7.feature2': 'Tapşırıqları tamamlanmış kimi qeyd et',
      'portfolio.project7.feature3': 'Local storage saxlanması',
      'portfolio.project8.title': 'Hava Tətbiqi',
      'portfolio.project8.desc': 'Cari hava şəraitini və proqnozları göstərən responsive hava tətbiqi. Real vaxt məlumatları üçün hava API-ləri ilə inteqrasiya.',
          'portfolio.project8.feature1': 'Cari hava göstəricisi',
    'portfolio.project8.feature2': 'Hava API inteqrasiyası',
    'portfolio.project8.feature3': 'Responsive dizayn',
    'portfolio.project9.title': 'Modern Portfolio Veb Saytı',
    'portfolio.project9.desc': 'React, TypeScript və Tailwind CSS ilə tikilmiş modern, responsive portfolio veb saytı. Smooth animasiyalar, çoxdilli dəstək və inkişaf bacarıqlarımı nümayiş etdirən interaktiv komponentlər.',
    'portfolio.project9.feature1': 'Çoxdilli dəstək (EN/AZ/TR)',
    'portfolio.project9.feature2': 'İnteraktiv animasiyalar və komponentlər',
    'portfolio.project9.feature3': 'Modern UI/UX ilə responsive dizayn',
    'portfolio.codeEditor': 'Canlı Kod Redaktoru',
    'portfolio.codeEditorDesc': 'Bu interaktiv kod nümunəsi ilə mənim kod yazma stilimi və yanaşmamı görün',
    'portfolio.codeEditor.hello': 'Salam',
    'portfolio.codeEditor.welcome': 'Portfolio-ma xoş gəlmisiniz',
    'portfolio.timeline': 'Öyrənmə Zaman Xətti',
    'portfolio.timelineDesc': 'Mənim inkişaf səfərim və zamanla öyrənmə tərəqqim',
    
    // Contact Section
    'contact.title': 'Əlaqə',
    'contact.subtitle': 'Layihələriniz üçün mənimlə əlaqə saxlayın.',
    'contact.getInTouch': 'Əlaqə Saxla',
    'contact.ready': 'Növbəti layihənizi başlamağa hazırsınız? Fikirlərinizi həyata keçirməkdə sizə necə kömək edə biləcəyimi müzakirə edək.',
    'contact.name': 'Ad',
    'contact.email': 'E-poçt',
    'contact.phone': 'Əlaqə nömrəsi',
    'contact.linkedin': 'LinkedIn',
    'contact.subject': 'Mövzu',
    'contact.message': 'Mesaj',
    'contact.sendMessage': 'Mesaj Göndər',
    'contact.sending': 'Göndərilir...',
    'contact.messageSent': 'Mesaj Göndərildi!',
    'contact.available': 'Layihələr üçün Mövcuddur',
    'contact.availableDesc': 'Hal-hazırda yeni imkanları qəbul edir',
    'contact.placeholder.name': 'Adınız',
    'contact.placeholder.email': 'sizin@email.com',
    'contact.placeholder.subject': 'Layihə sorğusu',
    'contact.placeholder.message': 'Layihəniz haqqında mənə danışın...',
    
    // Footer
    'footer.getInTouch': 'Əlaqə Saxla',
    'footer.ready': 'Sizin üçün web və mobil tətbiq layihələri. Cross-platform inkişaf sahəsində sizə kömək edə bilərəm.',
    'footer.quickLinks': 'Sürətli Linklər',
    'footer.contact': 'Əlaqə',
    'footer.workTogether': 'Gəlin Birlikdə İşləyək',
    'footer.workTogetherDesc': 'Növbəti layihənizi başlamağa hazırsınız? Fikirlərinizi həyata keçirməkdə sizə necə kömək edə biləcəyimi müzakirə edək.',
    'footer.copyright': '© 2025 Babək Qasımzadə. Bütün hüquqlar qorunur.',
    'footer.madeWith': 'Azərbaycanda ❤️ ilə BGDev tərəfindən hazırlanıb',
    'footer.description': 'Mobil və Frontend Developer kimi, mənimlə modern web texnologiyaları ilə istifadəçi dostu və işləməli tətbiqlər yaradıram. Cross-platform inkişaf sahəsində ixtisaslaşmağa çalışıram.',
    
    // About
    'about.badge': 'Mobil Developer',
  },
  tr: {
    // Navigation
    'nav.home': 'Ana Sayfa',
    'nav.about': 'Hakkımda',
    'nav.skills': 'Yetenekler',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'İletişim',
    
    // Hero Section
    'hero.title': 'Babək Qasımzadə',
    'hero.subtitle': 'React, React Native ve modern teknolojiler ile web ve mobil uygulamalar geliştiriyorum.',
    'hero.description': 'React Native, React ve modern web teknolojileri ile yenilikçi dijital deneyimler yaratan tutkulu Mobil ve Frontend Developer.',
    'hero.welcome': 'Portfolio\'ma hoş geldiniz',
    'hero.cta': 'İletişime Geç',
    'hero.cv': 'CV İndir',
    
    // About Section
    'about.title': 'Hakkımda',
    'about.subtitle': 'React, React Native ve modern web teknolojilerinde pratik deneyime sahip tutkulu bir Junior Frontend ve Mobil Developer\'ım.',
    'about.journey': 'Mobile ve Frontend Developer Olarak Yolculuğum',
    'about.description1': "JavaScript ve React ekosisteminde sağlam bir temelle, işlevsel ve kullanıcı dostu uygulamalar oluşturma yeteneğimi gösteren birkaç projeyi başarıyla tamamladım.",
    'about.description2': 'Temiz, iyi belgelenmiş kod yazmaya ve sürdürülebilir, verimli çözümler oluşturmak için en iyi uygulamaları takip etmeye odaklanıyorum.',
    'about.description3': 'Sürekli öğrenmeye ve endüstri trendleriyle güncel kalmaya bağlıyım, bu da modern, yüksek kaliteli uygulamalar sunmama yardımcı oluyor.',
    'about.focus': 'Odaklandığım Alanlar',
    'about.projects': 'Projeler',
    'about.projectsDesc': 'Kişisel ve eğitim projeleri',
    'about.teamProjects': 'Takım Projeleri',
    'about.teamProjectsDesc': 'Grup çalışmaları',
    'about.experience': 'Deneyim',
    'about.experienceDesc': 'Aktif öğrenme süreci',
    'about.experienceYear': '1 yıl',
    'about.service1': 'Responsive Web Design',
    'about.service2': 'React.js Applications',
    'about.service3': 'React Native Mobile Apps',
    'about.service4': 'Cross-platform Development',
    'about.service5': 'Modern UI/UX Design',
    'about.service6': 'Mobile App Deployment',
    
    // Skills Section
    'skills.title': 'Yeteneklerim',
    'skills.subtitle': 'Fikirleri hayata geçirmek için kullandığım teknolojiler ve araçlar',
    'skills.frontend': 'Frontend',
    'skills.mobile': 'Mobil Geliştirme',
    'skills.tools': 'Araçlar ve Diğerleri',
    'skills.technologies': 'Teknolojiler ve Seviyelerim',
    'skills.learning': 'Şu Anda Öğrendiklerim',
    'skills.learningDesc': 'Sürekli gelişim için aktif olarak öğrendiğim teknolojiler',
    'skills.level.good': 'İyi',
    'skills.level.veryGood': 'Çok İyi',
    'skills.level.medium': 'Orta',
    'skills.tech.react': 'React',
    'skills.tech.reactNative': 'React Native',
    'skills.tech.javascript': 'JavaScript',
    'skills.tech.htmlcss': 'HTML/CSS',
    'skills.tech.expo': 'Expo',
    'skills.tech.typescript': 'TypeScript',
    'skills.tech.figma': 'Figma',
    'skills.tech.tailwind': 'Tailwind',
    'skills.learning.flutter': 'Flutter',
    'skills.learning.swift': 'Swift',
    'skills.learning.kotlin': 'Kotlin',
    'skills.learning.nextjs': 'Next.js',
    'skills.learning.testing': 'Testing',
    'skills.treeTitle': 'Öğrenme Yolum',
    'skills.treeDesc': 'İnteraktif beceri ağacı gelişim yolculuğumu ve teknolojilerin nasıl bağlandığını gösterir',
    
    // Portfolio Section
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'Öğrenme yolculuğumu gösteren web geliştirme projelerimin koleksiyonu.',
    'portfolio.all': 'Tümü',
    'portfolio.web': 'Web',
'portfolio.mobile': 'Mobil',
'portfolio.responsive': 'Responsive',
'portfolio.interactive': 'İnteraktif',
    'portfolio.viewProject': 'Projeyi Görüntüle',
    'portfolio.viewCode': 'Kodu Görüntüle',
    'portfolio.technologies': 'Teknolojiler',
    'portfolio.features': 'Özellikler',
    'portfolio.liveDemo': 'Canlı Demo',
    'portfolio.github': 'GitHub',
    'portfolio.viewDetails': 'Detayları Görüntüle',
    'portfolio.moreProjects': 'Daha çok proje görmek ister misiniz?',
    'portfolio.moreProjectsDesc': 'GitHub profilimde daha çok projeyi bulabilirsiniz.',
    'portfolio.githubProfile': 'GitHub Profilim',
    'portfolio.project1.title': 'BGAutoSales - E-ticaret Platformu',
    'portfolio.project1.desc': 'Küçük işletmem için HTML5, CSS3 ve JavaScript ile yaratılmış tam e-ticaret web sitesi. Ürün kataloğu, alışveriş sepeti ve mobil ve masaüstü kullanıcılar için responsive tasarım.',
    'portfolio.project1.feature1': 'Ürün kataloğu ve arama',
    'portfolio.project1.feature2': 'Alışveriş sepeti işlevi',
    'portfolio.project1.feature3': 'Responsive mobil tasarım',
    'portfolio.project1.feature4': 'Ödeme entegrasyonu hazır',
    'portfolio.project2.title': 'Buldum App - Pazar Yeri Platformu',
    'portfolio.project2.desc': 'Araba, emlak ve cihazların satışı için profesyonel pazar yeri uygulaması. "İlan ver" özelliğini kategoriler, alt kategoriler, API entegrasyonu ve gelişmiş işlevsellik ile geliştirdim.',
    'portfolio.project2.feature1': 'İlan verme işlevi',
    'portfolio.project2.feature2': 'Kategori yönetimi',
    'portfolio.project2.feature3': 'API entegrasyonu',
    'portfolio.project2.feature4': 'Gelişmiş arama filtreleri',
    'portfolio.project3.title': 'UDEMY-BG - Öğrenme Platformu Klonu',
    'portfolio.project3.desc': 'React, Node.js ve MongoDB ile yaratılmış tam yığın Udemy klonu. Kullanıcı kimlik doğrulaması, kurs yönetimi, video yayını ve ödeme işleme.',
    'portfolio.project3.feature1': 'Kullanıcı kimlik doğrulaması',
    'portfolio.project3.feature2': 'Kurs yönetimi',
    'portfolio.project3.feature3': 'Video yayını',
    'portfolio.project3.feature4': 'Ödeme entegrasyonu',
    'portfolio.project4.title': 'Vesh.az - Seyahat Platformu',
    'portfolio.project4.desc': 'Bakü\'de 80k+ kullanıcısı olan ana seyahat platformu. Hem web hem de mobil uygulama geliştirmede katkıda bulundum, UI/UX tasarımına odaklanarak. Google Play Store ve App Store\'da mevcuttur.',
    'portfolio.project4.feature1': 'Responsive web tasarımı',
    'portfolio.project4.feature2': 'Mobil uygulama UI/UX',
    'portfolio.project4.feature3': 'Seyahat rezervasyon arayüzü',
    'portfolio.project4.feature4': 'Cross-platform uyumluluk',
    'portfolio.project5.title': 'E-Öneri Sistemi - Tez',
    'portfolio.project5.desc': 'Lisans tez projesi: Python ve Flask ile yaratılmış akıllı öneri sistemi. Kişiselleştirilmiş içerik önerileri için makine öğrenmesi algoritmalarını uygular.',
    'portfolio.project5.feature1': 'Makine öğrenmesi algoritmaları',
    'portfolio.project5.feature2': 'Öneri motoru',
    'portfolio.project5.feature3': 'Veri analizi',
    'portfolio.project5.feature4': 'Akademik araştırma',
    'portfolio.project6.title': 'Frontend Portfolio',
    'portfolio.project6.desc': 'Frontend development becerilerimi sergileyen önceki portfolio web sitem. HTML5, CSS3 ve JavaScript ile yaratılmış, modern tasarım ve smooth animasyonlar.',
          'portfolio.project6.feature1': 'Modern portfolio tasarımı',
      'portfolio.project6.feature2': 'Smooth animasyonlar',
      'portfolio.project6.feature3': 'Responsive layout',
      'portfolio.project6.feature4': 'İnteraktif elementler',
      'portfolio.project7.title': 'Todo List Uygulaması',
      'portfolio.project7.desc': 'Vanilla JavaScript ile yapılmış basit ve sezgisel todo list uygulaması. Görev oluşturma, tamamlama takibi ve veri kalıcılığı için local storage özellikleri.',
      'portfolio.project7.feature1': 'Görev ekle ve sil',
      'portfolio.project7.feature2': 'Görevleri tamamlandı olarak işaretle',
      'portfolio.project7.feature3': 'Local storage kalıcılığı',
      'portfolio.project8.title': 'Hava Durumu Uygulaması',
      'portfolio.project8.desc': 'Mevcut hava durumunu ve tahminleri gösteren responsive hava uygulaması. Gerçek zamanlı veri sağlamak için hava API\'leri ile entegrasyon.',
          'portfolio.project8.feature1': 'Mevcut hava durumu gösterimi',
    'portfolio.project8.feature2': 'Hava API entegrasyonu',
    'portfolio.project8.feature3': 'Responsive tasarım',
    'portfolio.project9.title': 'Modern Portfolio Web Sitesi',
    'portfolio.project9.desc': 'React, TypeScript ve Tailwind CSS ile inşa edilmiş modern, responsive portfolio web sitesi. Smooth animasyonlar, çok dilli destek ve geliştirme becerilerimi sergileyen interaktif bileşenler.',
    'portfolio.project9.feature1': 'Çok dilli destek (EN/AZ/TR)',
    'portfolio.project9.feature2': 'İnteraktif animasyonlar ve bileşenler',
    'portfolio.project9.feature3': 'Modern UI/UX ile responsive tasarım',
    'portfolio.codeEditor': 'Canlı Kod Editörü',
    'portfolio.codeEditorDesc': 'Bu interaktif kod örneği ile kod yazma stilimi ve yaklaşımımı görün',
    'portfolio.codeEditor.hello': 'Merhaba',
    'portfolio.codeEditor.welcome': 'Portfolio\'ma hoş geldiniz',
    'portfolio.timeline': 'Öğrenme Zaman Çizelgesi',
    'portfolio.timelineDesc': 'Gelişim yolculuğum ve zamanla öğrenme ilerlemem',
    
    // Contact Section
    'contact.title': 'İletişim',
    'contact.subtitle': 'Projeleriniz için benimle iletişime geçin.',
    'contact.getInTouch': 'İletişime Geç',
    'contact.ready': 'Bir sonraki projenizi başlatmaya hazır mısınız? Fikirlerinizi hayata geçirmenize nasıl yardımcı olabileceğimi tartışalım.',
    'contact.name': 'Ad',
    'contact.email': 'E-posta',
    'contact.phone': 'Telefon',
    'contact.linkedin': 'LinkedIn',
    'contact.subject': 'Konu',
    'contact.message': 'Mesaj',
    'contact.sendMessage': 'Mesaj Gönder',
    'contact.sending': 'Gönderiliyor...',
    'contact.messageSent': 'Mesaj Gönderildi!',
    'contact.available': 'Projeler İçin Müsait',
    'contact.availableDesc': 'Şu anda yeni fırsatları kabul ediyor',
    'contact.placeholder.name': 'Adınız',
    'contact.placeholder.email': 'sizin@email.com',
    'contact.placeholder.subject': 'Proje sorgusu',
    'contact.placeholder.message': 'Projeniz hakkında bana anlatın...',
    
    // Footer
    'footer.getInTouch': 'İletişime Geç',
    'footer.ready': 'Sizin için web ve mobil uygulama projeleri. Cross-platform geliştirme konusunda size yardımcı olabilirim.',
    'footer.quickLinks': 'Hızlı Linkler',
    'footer.contact': 'İletişim',
    'footer.workTogether': 'Birlikte Çalışalım',
    'footer.workTogetherDesc': 'Bir sonraki projenizi başlatmaya hazır mısınız? Fikirlerinizi hayata geçirmenize nasıl yardımcı olabileceğimi tartışalım.',
    'footer.copyright': '© 2025 Babək Qasımzadə. Tüm hakları saklıdır.',
    'footer.madeWith': 'Azerbaycan\'da ❤️ ile BGDev tarafından yapıldı',
    'footer.description': 'Mobil ve Frontend Developer kimi, mənimlə modern web texnologiyaları ilə istifadəçi dostu və işləməli tətbiqlər yaradıram. Cross-platform geliştirme konusunda size yardımcı olabilirim.',
    
    // About
    'about.badge': 'Mobil Developer',
  },
};

export const LanguageProvider = ({ children }: { children: any }) => {
  const [language, setLanguage] = useState('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 